# Generated by Django 4.1.2 on 2022-12-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_narudzbe', models.DateTimeField(auto_now_add=True)),
                ('adresa_isporuke', models.CharField(max_length=200)),
                ('placena', models.BooleanField(default=False)),
                ('kosarica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.kosarica')),
            ],
        ),
    ]
